### ISSUE TITLE
Car swerves off road into buildings

### ISSUE THREAD

**Issue by nickw409** [nickw409/cs386-a1#3]
In self driving mode, the car swerves off the road at random and drives into building, real inconvenience.

**Comment by kimberlyrallison** [comment]
We need an emergency stop system that will engage when an obstacle is detected.

**Comment by nickw409** [comment]
Fix now

**Comment by kimberlyrallison** [comment]
@psw35 How do you think we should fix this?

**Comment by kimberlyrallison** [comment]
This issue seems connected to issue #2

**Comment by nickw409** [comment]
#2  This is similar in issue, should be able to fix both.

**Comment by nickw409** [comment]
Done
